# Generated by Django 2.1.7 on 2019-05-09 13:22

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20190509_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=martor.models.MartorField(),
        ),
    ]
