# Generated by Django 2.1.7 on 2019-05-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20190509_1636'),
        ('accounts', '0002_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(related_name='followers', to='accounts.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='saved_posts',
            field=models.ManyToManyField(related_name='saved_by', to='posts.Post'),
        ),
    ]
