# Generated by Django 2.1.7 on 2019-05-15 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190515_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='saved_posts',
        ),
    ]
