# Generated by Django 2.1.7 on 2019-05-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190515_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(related_name='followers', to='accounts.Profile'),
        ),
    ]
